import 'package:eiga/backend/database/schemas/language.dart';

Future<List<Language>> standardLanguages() async {
  return [
    Language(
      name: 'Japanese',
      code: 'ja',
      subtitle: 'Jpn / 日本語',
      iconLabel: 'JA',
      isSupported: true,
      removeAllSpaces: true,
      tokenizationMethod: TokenizationMethod.ai,
      readingOptions: ['original', 'kana', 'romaji'],
      readingLabels: ['KANJI', 'KANA', 'ROMAJI'],
      spacingOptions: ['romaji'],
    ),
    Language(
      name: 'English',
      code: 'en',
      subtitle: 'Eng / United States',
      iconLabel: 'EN',
      isSupported: false,
      removeAllSpaces: false,
      tokenizationMethod: TokenizationMethod.local,
      readingOptions: ['original'],
      readingLabels: ['ORIGINAL'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Spanish',
      code: 'es',
      subtitle: 'Spain / Español',
      iconLabel: 'ES',
      isSupported: false,
      removeAllSpaces: false,
      tokenizationMethod: TokenizationMethod.local,
      readingOptions: ['original'],
      readingLabels: ['ORIGINAL'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Ukrainian',
      code: 'uk',
      subtitle: 'Ukr / Українська',
      iconLabel: 'UA',
      isSupported: false,
      removeAllSpaces: false,
      tokenizationMethod: TokenizationMethod.local,
      readingOptions: ['original'],
      readingLabels: ['ORIGINAL'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Russian',
      code: 'ru',
      subtitle: 'Ru / Русский',
      iconLabel: 'RU',
      isSupported: false,
      removeAllSpaces: false,
      tokenizationMethod: TokenizationMethod.local,
      readingOptions: ['original'],
      readingLabels: ['ORIGINAL'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'German',
      code: 'de',
      subtitle: 'Ger / Deutsch',
      iconLabel: 'DE',
      isSupported: false,
      removeAllSpaces: false,
      tokenizationMethod: TokenizationMethod.local,
      readingOptions: ['original'],
      readingLabels: ['ORIGINAL'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'French',
      code: 'fr',
      subtitle: 'Fra / Français',
      iconLabel: 'FR',
      isSupported: false,
      removeAllSpaces: false,
      tokenizationMethod: TokenizationMethod.local,
      readingOptions: ['original'],
      readingLabels: ['ORIGINAL'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Italian',
      code: 'it',
      subtitle: 'Ita / Italiano',
      iconLabel: 'IT',
      isSupported: false,
      removeAllSpaces: false,
      tokenizationMethod: TokenizationMethod.local,
      readingOptions: ['original'],
      readingLabels: ['ORIGINAL'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Chinese',
      code: 'zh',
      subtitle: 'Chi / 中文',
      iconLabel: 'ZH',
      isSupported: false,
      removeAllSpaces: true,
      tokenizationMethod: TokenizationMethod.local,
      readingOptions: ['original'],
      readingLabels: ['ORIGINAL'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Korean',
      code: 'ko',
      subtitle: 'Kor / 한국어',
      iconLabel: 'KO',
      isSupported: false,
      removeAllSpaces: true,
      tokenizationMethod: TokenizationMethod.local,
      readingOptions: ['original'],
      readingLabels: ['ORIGINAL'],
      spacingOptions: ['original'],
    ),
  ];
}
