import 'package:eiga/backend/database/schemas/language.dart';

Future<List<Language>> standardLanguages() async {
  return [
    Language(
      name: 'Japanese',
      code: 'ja',
      isSupported: true,
      removeAllSpaces: true,
      readingOptions: ['original', 'kana', 'romaji'],
      spacingOptions: ['romaji'],
    ),
    Language(
      name: 'English',
      code: 'en',
      isSupported: false,
      removeAllSpaces: false,
      readingOptions: ['original'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Spanish',
      code: 'es',
      isSupported: false,
      removeAllSpaces: false,
      readingOptions: ['original'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Ukrainian',
      code: 'uk',
      isSupported: false,
      removeAllSpaces: false,
      readingOptions: ['original'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Russian',
      code: 'ru',
      isSupported: false,
      removeAllSpaces: false,
      readingOptions: ['original'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'German',
      code: 'de',
      isSupported: false,
      removeAllSpaces: false,
      readingOptions: ['original'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'French',
      code: 'fr',
      isSupported: false,
      removeAllSpaces: false,
      readingOptions: ['original'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Italian',
      code: 'it',
      isSupported: false,
      removeAllSpaces: false,
      readingOptions: ['original'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Chinese',
      code: 'zh',
      isSupported: false,
      removeAllSpaces: true,
      readingOptions: ['original'],
      spacingOptions: ['original'],
    ),
    Language(
      name: 'Korean',
      code: 'ko',
      isSupported: false,
      removeAllSpaces: true,
      readingOptions: ['original'],
      spacingOptions: ['original'],
    ),
  ];
}
